# Generated by Django 5.0.1 on 2024-08-09 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("9eff2c51-a031-4941-ad53-c0f5714bf5bb"),
                editable=False,
                unique=True,
            ),
        ),
    ]
