# Generated by Django 5.1 on 2024-08-10 02:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_user", "0002_alter_user_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("40d2db89-b1b2-4a81-9b67-b036bfe8524b"),
                editable=False,
                unique=True,
            ),
        ),
    ]
